/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package julja.gms;

import org.junit.Test;

public class ClientAppTest {
  @Test
  public void test() {
    System.out.println("This is a Test App for Client.");
  }
}
